plugins {
    id 'com.android.application'
}

android {
    namespace 'com.customfolders.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.customfolders.app'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
