package com.customfolders.app;
import android.app.*;import android.appwidget.AppWidgetManager;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.Drawable;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;
public class EditorActivity extends Activity{
 static final int REQ_BG=10,REQ_ICON=11;FolderStore store;FolderStore.Folder f;ImageView preview;EditText name,color,emoji;SeekBar opacity,iconSize;Spinner shape,previewCount,grid,popupSize,anim,preset,template;CheckBox showTitle,glass;LinearLayout appsBox;ArrayList<AppInfo> installed=new ArrayList<>();
 static class AppInfo{String pkg,label;Drawable icon;boolean system;AppInfo(String p,String l,Drawable i,boolean s){pkg=p;label=l;icon=i;system=s;}}
 @Override public void onCreate(Bundle b){ThemeUtils.apply(this);super.onCreate(b);store=new FolderStore(this);long id=getIntent().getLongExtra("folderId",-1);f=id>0?store.get(id):new FolderStore.Folder();if(f==null)f=new FolderStore.Folder();loadApps();build();fill();}
 void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,26));root.setBackgroundColor(ThemeUtils.bg(this));sv.addView(root,new ScrollView.LayoutParams(-1,-2));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button back=Ui.button(this,"←",false);top.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,42)));TextView title=Ui.text(this,f.id>0?"Редагування папки":"Нова папка",24,ThemeUtils.text(this));title.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);Ui.margins(tp,this,10,0,0,0);top.addView(title,tp);root.addView(top,Ui.mp(this));back.setOnClickListener(v->finish());
 preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,Ui.dp(this,190));Ui.margins(pp,this,0,12,0,4);root.addView(preview,pp);
 section(root,"Основне");name=Ui.input(this,"Назва папки");name.setSingleLine(true);root.addView(name,Ui.mp(this));LinearLayout colRow=new LinearLayout(this);colRow.setGravity(Gravity.CENTER_VERTICAL);color=Ui.input(this,"#6C63FF");color.setSingleLine(true);colRow.addView(color,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));Button bg=Ui.button(this,"Фон",false);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-2,Ui.dp(this,50));Ui.margins(bp,this,8,0,0,0);colRow.addView(bg,bp);Button clearBg=Ui.button(this,"×",false);LinearLayout.LayoutParams cbp=new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,50));Ui.margins(cbp,this,6,0,0,0);colRow.addView(clearBg,cbp);LinearLayout.LayoutParams crp=Ui.mp(this);Ui.margins(crp,this,0,8,0,0);root.addView(colRow,crp);bg.setOnClickListener(v->pickImage(REQ_BG));clearBg.setOnClickListener(v->{f.bgUri="";updatePreview();});
 label(root,"Прозорість");opacity=new SeekBar(this);opacity.setMax(225);root.addView(opacity,Ui.mp(this));label(root,"Форма");shape=spinner(new String[]{"Закруглена","Квадрат","Коло"});root.addView(shape,Ui.mp(this));
 section(root,"Іконка");LinearLayout ir=new LinearLayout(this);ir.setGravity(Gravity.CENTER_VERTICAL);emoji=Ui.input(this,"Emoji, наприклад 🎮");emoji.setSingleLine(true);ir.addView(emoji,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));Button ownIcon=Ui.button(this,"Зображення",false);LinearLayout.LayoutParams oi=new LinearLayout.LayoutParams(-2,Ui.dp(this,50));Ui.margins(oi,this,8,0,0,0);ir.addView(ownIcon,oi);root.addView(ir,Ui.mp(this));ownIcon.setOnClickListener(v->pickImage(REQ_ICON));showTitle=check("Показувати назву на віджеті");root.addView(showTitle,Ui.mp(this));label(root,"Іконок у прев’ю");previewCount=spinner(new String[]{"4","6","9"});root.addView(previewCount,Ui.mp(this));
 section(root,"Готовий стиль");preset=spinner(new String[]{"Не змінювати","Glass","Minimal","Neon","Dark","Pastel"});root.addView(preset,Ui.mp(this));Button apply=Ui.button(this,"Застосувати стиль",false);LinearLayout.LayoutParams apl=Ui.mp(this);Ui.margins(apl,this,0,6,0,0);root.addView(apply,apl);apply.setOnClickListener(v->applyPreset(preset.getSelectedItemPosition()));
 section(root,"Програми");Button addApps=Ui.button(this,"+ Додати / прибрати програми",true);root.addView(addApps,new LinearLayout.LayoutParams(-1,Ui.dp(this,50)));TextView ah=Ui.text(this,"Порядок можна змінювати стрілками. Одна програма може бути в кількох папках.",12,ThemeUtils.sub(this));LinearLayout.LayoutParams ahp=Ui.mp(this);Ui.margins(ahp,this,0,6,0,5);root.addView(ah,ahp);appsBox=new LinearLayout(this);appsBox.setOrientation(LinearLayout.VERTICAL);root.addView(appsBox,Ui.mp(this));addApps.setOnClickListener(v->showAppPicker());
 section(root,"Відкрита папка");label(root,"Сітка");grid=spinner(new String[]{"3 × 3","4 × 4","5 × 5"});root.addView(grid,Ui.mp(this));label(root,"Розмір іконок");iconSize=new SeekBar(this);iconSize.setMax(60);root.addView(iconSize,Ui.mp(this));label(root,"Розмір вікна");popupSize=spinner(new String[]{"Малий","Середній","Великий"});root.addView(popupSize,Ui.mp(this));label(root,"Анімація відкриття");anim=spinner(new String[]{"Zoom","Fade","Slide Up","Spring","Без анімації"});root.addView(anim,Ui.mp(this));glass=check("Напівпрозорий фон + ефект скла, якщо підтримується");root.addView(glass,Ui.mp(this));
 section(root,"Шаблон");LinearLayout tr=new LinearLayout(this);template=spinner(templateNames());tr.addView(template,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));Button load=Ui.button(this,"Застосувати",false);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,Ui.dp(this,50));Ui.margins(lp,this,8,0,0,0);tr.addView(load,lp);root.addView(tr,Ui.mp(this));Button saveTemplate=Ui.button(this,"Зберегти стиль як шаблон",false);LinearLayout.LayoutParams stp=Ui.mp(this);Ui.margins(stp,this,0,7,0,0);root.addView(saveTemplate,stp);load.setOnClickListener(v->applyTemplate(template.getSelectedItemPosition()-1));saveTemplate.setOnClickListener(v->saveTemplate());
 Button save=Ui.button(this,"Зберегти папку",true);LinearLayout.LayoutParams sap=new LinearLayout.LayoutParams(-1,Ui.dp(this,54));Ui.margins(sap,this,0,20,0,0);root.addView(save,sap);Button pin=Ui.button(this,"Додати на робочий стіл",false);LinearLayout.LayoutParams pip=new LinearLayout.LayoutParams(-1,Ui.dp(this,52));Ui.margins(pip,this,0,8,0,0);root.addView(pin,pip);save.setOnClickListener(v->{capture();store.save(f);FolderWidgetProvider.updateAll(this);Toast.makeText(this,"Папку збережено",Toast.LENGTH_SHORT).show();});pin.setOnClickListener(v->{capture();store.save(f);FolderWidgetProvider.updateAll(this);pinWidget();});setContentView(sv);watch();}
 void fill(){name.setText(f.name);color.setText(f.color);emoji.setText(f.emoji);opacity.setProgress(Math.max(0,f.opacity-30));shape.setSelection("circle".equals(f.shape)?2:"square".equals(f.shape)?1:0);previewCount.setSelection(f.previewCount==9?2:f.previewCount==6?1:0);showTitle.setChecked(f.showTitle);grid.setSelection(f.grid==5?2:f.grid==3?0:1);iconSize.setProgress(Math.max(0,f.iconSize-40));popupSize.setSelection("large".equals(f.popupSize)?2:"small".equals(f.popupSize)?0:1);anim.setSelection("fade".equals(f.animation)?1:"slide".equals(f.animation)?2:"spring".equals(f.animation)?3:"none".equals(f.animation)?4:0);glass.setChecked(f.glass);refreshApps();updatePreview();}
 void watch(){TextWatcher tw=new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){captureLight();updatePreview();}public void afterTextChanged(Editable e){}};name.addTextChangedListener(tw);color.addTextChangedListener(tw);emoji.addTextChangedListener(tw);opacity.setOnSeekBarChangeListener(simpleSeek());shape.setOnItemSelectedListener(simpleSelect());previewCount.setOnItemSelectedListener(simpleSelect());showTitle.setOnCheckedChangeListener((b,c)->updatePreview());}
 SeekBar.OnSeekBarChangeListener simpleSeek(){return new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f1){captureLight();updatePreview();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}};} android.widget.AdapterView.OnItemSelectedListener simpleSelect(){return new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>a,View v,int p,long id){captureLight();updatePreview();}public void onNothingSelected(android.widget.AdapterView<?>a){}};}
 void captureLight(){if(name==null)return;f.name=name.getText().toString().trim().isEmpty()?"Папка":name.getText().toString().trim();String c=color.getText().toString().trim();try{Color.parseColor(c);f.color=c;}catch(Exception ignored){}f.emoji=emoji.getText().toString();f.opacity=30+opacity.getProgress();f.shape=shape.getSelectedItemPosition()==2?"circle":shape.getSelectedItemPosition()==1?"square":"rounded";f.previewCount=previewCount.getSelectedItemPosition()==2?9:previewCount.getSelectedItemPosition()==1?6:4;f.showTitle=showTitle.isChecked();}
 void capture(){captureLight();f.grid=grid.getSelectedItemPosition()==2?5:grid.getSelectedItemPosition()==0?3:4;f.iconSize=40+iconSize.getProgress();f.popupSize=popupSize.getSelectedItemPosition()==2?"large":popupSize.getSelectedItemPosition()==0?"small":"medium";String[] an={"zoom","fade","slide","spring","none"};f.animation=an[anim.getSelectedItemPosition()];f.glass=glass.isChecked();}
 void updatePreview(){if(preview==null)return;preview.setImageBitmap(WidgetRenderer.render(this,f,Ui.dp(this,260),Ui.dp(this,170)));}
 Spinner spinner(String[] a){Spinner s=new Spinner(this);ArrayAdapter<String>x=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,a);x.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(x);return s;}CheckBox check(String s){CheckBox c=new CheckBox(this);c.setText(s);c.setTextColor(ThemeUtils.text(this));c.setTextSize(14);return c;}void label(LinearLayout r,String s){TextView t=Ui.text(this,s,13,ThemeUtils.sub(this));LinearLayout.LayoutParams p=Ui.mp(this);Ui.margins(p,this,1,9,0,4);r.addView(t,p);}void section(LinearLayout r,String s){TextView t=Ui.text(this,s,15,ThemeUtils.text(this));t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams p=Ui.mp(this);Ui.margins(p,this,0,18,0,7);r.addView(t,p);}
 void pickImage(int req){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,req);}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}if(req==REQ_BG)f.bgUri=u.toString();else if(req==REQ_ICON)f.iconUri=u.toString();updatePreview();}
 void loadApps(){PackageManager pm=getPackageManager();Intent i=new Intent(Intent.ACTION_MAIN);i.addCategory(Intent.CATEGORY_LAUNCHER);HashSet<String> seen=new HashSet<>();for(ResolveInfo r:pm.queryIntentActivities(i,0)){String p=r.activityInfo.packageName;if(seen.add(p)){ApplicationInfo ai=r.activityInfo.applicationInfo;installed.add(new AppInfo(p,r.loadLabel(pm).toString(),r.loadIcon(pm),(ai.flags&ApplicationInfo.FLAG_SYSTEM)!=0));}}installed.sort(Comparator.comparing(a->a.label.toLowerCase(Locale.ROOT)));}
 void showAppPicker(){Dialog d=new Dialog(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14));root.setBackgroundColor(ThemeUtils.bg(this));EditText q=Ui.input(this,"Пошук програм…");q.setSingleLine(true);root.addView(q,new LinearLayout.LayoutParams(-1,Ui.dp(this,50)));CheckBox sys=check("Показувати системні програми");root.addView(sys,Ui.mp(this));ListView lv=new ListView(this);AppAdapter ad=new AppAdapter(installed,false);lv.setAdapter(ad);root.addView(lv,new LinearLayout.LayoutParams(-1,0,1));Button done=Ui.button(this,"Готово",true);root.addView(done,new LinearLayout.LayoutParams(-1,Ui.dp(this,50)));d.setContentView(root);Window w=d.getWindow();if(w!=null)w.setLayout(-1,(int)(getResources().getDisplayMetrics().heightPixels*.82));q.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){ad.filter(s.toString(),sys.isChecked());}public void afterTextChanged(Editable e){}});sys.setOnCheckedChangeListener((b,c)->ad.filter(q.getText().toString(),c));done.setOnClickListener(v->{d.dismiss();refreshApps();updatePreview();});d.show();if(d.getWindow()!=null)d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94),(int)(getResources().getDisplayMetrics().heightPixels*.84));}
 class AppAdapter extends BaseAdapter{ArrayList<AppInfo> data=new ArrayList<>();String query="";boolean system=false;AppAdapter(List<AppInfo>a,boolean s){filter("",s);}void filter(String q,boolean sys){query=q.toLowerCase(Locale.ROOT);system=sys;data.clear();for(AppInfo a:installed)if((sys||!a.system)&&a.label.toLowerCase(Locale.ROOT).contains(query))data.add(a);notifyDataSetChanged();}public int getCount(){return data.size();}public Object getItem(int p){return data.get(p);}public long getItemId(int p){return p;}public View getView(int p,View v,android.view.ViewGroup parent){AppInfo a=data.get(p);LinearLayout row=new LinearLayout(EditorActivity.this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(Ui.dp(EditorActivity.this,6),Ui.dp(EditorActivity.this,5),Ui.dp(EditorActivity.this,6),Ui.dp(EditorActivity.this,5));ImageView im=new ImageView(EditorActivity.this);im.setImageDrawable(a.icon);row.addView(im,new LinearLayout.LayoutParams(Ui.dp(EditorActivity.this,42),Ui.dp(EditorActivity.this,42)));TextView t=Ui.text(EditorActivity.this,a.label,15,ThemeUtils.text(EditorActivity.this));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);Ui.margins(tp,EditorActivity.this,9,0,0,0);row.addView(t,tp);CheckBox c=new CheckBox(EditorActivity.this);c.setChecked(f.packages.contains(a.pkg));c.setOnCheckedChangeListener((b,ch)->{if(ch&&!f.packages.contains(a.pkg))f.packages.add(a.pkg);else if(!ch)f.packages.remove(a.pkg);});row.addView(c,new LinearLayout.LayoutParams(-2,-2));return row;}}
 void refreshApps(){if(appsBox==null)return;appsBox.removeAllViews();PackageManager pm=getPackageManager();for(int i=0;i<f.packages.size();i++){String pkg=f.packages.get(i);String lab=pkg;Drawable ic=null;try{ApplicationInfo ai=pm.getApplicationInfo(pkg,0);lab=pm.getApplicationLabel(ai).toString();ic=pm.getApplicationIcon(ai);}catch(Exception ignored){}LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);if(ic!=null){ImageView iv=new ImageView(this);iv.setImageDrawable(ic);row.addView(iv,new LinearLayout.LayoutParams(Ui.dp(this,36),Ui.dp(this,36)));}TextView t=Ui.text(this,lab,14,ThemeUtils.text(this));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);Ui.margins(tp,this,8,0,0,0);row.addView(t,tp);Button up=Ui.button(this,"↑",false),down=Ui.button(this,"↓",false),del=Ui.button(this,"×",false);row.addView(up,new LinearLayout.LayoutParams(Ui.dp(this,43),Ui.dp(this,40)));row.addView(down,new LinearLayout.LayoutParams(Ui.dp(this,43),Ui.dp(this,40)));row.addView(del,new LinearLayout.LayoutParams(Ui.dp(this,43),Ui.dp(this,40)));final int idx=i;up.setOnClickListener(v->{if(idx>0){Collections.swap(f.packages,idx,idx-1);refreshApps();updatePreview();}});down.setOnClickListener(v->{if(idx<f.packages.size()-1){Collections.swap(f.packages,idx,idx+1);refreshApps();updatePreview();}});del.setOnClickListener(v->{f.packages.remove(idx);refreshApps();updatePreview();});appsBox.addView(row,Ui.mp(this));}}
 void applyPreset(int p){if(p==1){f.color="#DDEBFF";f.opacity=150;f.shape="rounded";f.emoji="◈";f.glass=true;}else if(p==2){f.color="#2D2F36";f.opacity=245;f.shape="rounded";f.emoji="";f.glass=false;}else if(p==3){f.color="#6A00FF";f.opacity=235;f.shape="rounded";f.emoji="✦";f.glass=false;}else if(p==4){f.color="#111218";f.opacity=245;f.shape="rounded";f.emoji="●";f.glass=true;}else if(p==5){f.color="#D98CB3";f.opacity=220;f.shape="rounded";f.emoji="✿";f.glass=false;}fill();}
 String[] templateNames(){JSONArray a=store.templates();String[] out=new String[a.length()+1];out[0]="Оберіть шаблон";for(int i=0;i<a.length();i++)out[i+1]=a.optJSONObject(i).optString("templateName","Шаблон "+(i+1));return out;}
 void applyTemplate(int idx){if(idx<0)return;JSONObject o=store.templates().optJSONObject(idx);if(o==null)return;ArrayList<String> keep=new ArrayList<>(f.packages);long id=f.id;f=FolderStore.Folder.from(o);f.id=id;f.packages.addAll(keep);fill();}
 void saveTemplate(){final EditText e=Ui.input(this,"Назва шаблону");new AlertDialog.Builder(this).setTitle("Зберегти шаблон").setView(e).setNegativeButton("Скасувати",null).setPositiveButton("Зберегти",(d,w)->{capture();String n=e.getText().toString().trim();if(n.isEmpty())n="Мій шаблон";store.saveTemplate(n,f);Toast.makeText(this,"Шаблон збережено",Toast.LENGTH_SHORT).show();}).show();}
 void pinWidget(){if(Build.VERSION.SDK_INT>=26){AppWidgetManager m=AppWidgetManager.getInstance(this);ComponentName p=new ComponentName(this,FolderWidgetProvider.class);if(m.isRequestPinAppWidgetSupported()){getSharedPreferences("settings",0).edit().putLong("pending_pin",f.id).apply();m.requestPinAppWidget(p,null,null);Toast.makeText(this,"Підтвердь додавання на робочий стіл",Toast.LENGTH_LONG).show();return;}}Toast.makeText(this,"Додай віджет через меню віджетів HyperOS",Toast.LENGTH_LONG).show();}
}
