package com.customfolders.app;
import android.app.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.view.animation.*;import android.widget.*;import java.util.*;
public class FolderPopupActivity extends Activity{
 FolderStore.Folder f;
 @Override public void onCreate(Bundle b){super.onCreate(b);long id=getIntent().getLongExtra("folderId",-1);f=new FolderStore(this).get(id);if(f==null){finish();return;}if(Build.VERSION.SDK_INT>=31&&f.glass){try{getWindow().addFlags(WindowManager.LayoutParams.FLAG_BLUR_BEHIND);WindowManager.LayoutParams lp=getWindow().getAttributes();lp.setBlurBehindRadius(Ui.dp(this,22));getWindow().setAttributes(lp);}catch(Exception ignored){}}build();}
 void build(){FrameLayout outer=new FrameLayout(this);outer.setBackgroundColor(Color.TRANSPARENT);outer.setOnClickListener(v->finish());LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,12));int base;try{base=Color.parseColor(f.color);}catch(Exception e){base=Color.rgb(108,99,255);}int alpha=f.glass?Math.min(225,Math.max(120,f.opacity)):Math.max(180,f.opacity);GradientDrawable bg=Ui.round(this,Color.argb(alpha,Color.red(base),Color.green(base),Color.blue(base)),"circle".equals(f.shape)?38:"square".equals(f.shape)?6:22);panel.setBackground(bg);Bitmap ph=WidgetRenderer.loadUri(this,f.bgUri);if(ph!=null){BitmapDrawable bd=new BitmapDrawable(getResources(),ph);bd.setAlpha(Math.min(170,f.opacity));panel.setForeground(bd);}panel.setOnClickListener(v->{});
 LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView title=Ui.text(this,f.name,20,Color.WHITE);title.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button edit=Ui.button(this,"Редагувати",false);edit.setTextColor(Color.WHITE);head.addView(edit,new LinearLayout.LayoutParams(-2,Ui.dp(this,42)));panel.addView(head,Ui.mp(this));edit.setOnClickListener(v->{startActivity(new Intent(this,EditorActivity.class).putExtra("folderId",f.id));finish();});
 ScrollView sv=new ScrollView(this);GridLayout grid=new GridLayout(this);grid.setColumnCount(Math.max(3,Math.min(5,f.grid)));grid.setAlignmentMode(GridLayout.ALIGN_BOUNDS);PackageManager pm=getPackageManager();for(String pkg:f.packages){Intent launch=pm.getLaunchIntentForPackage(pkg);if(launch==null)continue;ApplicationInfo ai;try{ai=pm.getApplicationInfo(pkg,0);}catch(Exception e){continue;}String label=pm.getApplicationLabel(ai).toString();Drawable icon;try{icon=pm.getApplicationIcon(ai);}catch(Exception e){continue;}LinearLayout item=new LinearLayout(this);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);item.setPadding(Ui.dp(this,5),Ui.dp(this,8),Ui.dp(this,5),Ui.dp(this,8));ImageView iv=new ImageView(this);iv.setImageDrawable(icon);int is=Ui.dp(this,Math.max(44,Math.min(88,f.iconSize)));item.addView(iv,new LinearLayout.LayoutParams(is,is));TextView tv=Ui.text(this,label,11,Color.WHITE);tv.setGravity(Gravity.CENTER);tv.setMaxLines(2);LinearLayout.LayoutParams tvp=new LinearLayout.LayoutParams(-1,-2);Ui.margins(tvp,this,0,4,0,0);item.addView(tv,tvp);GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=-2;gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);item.setLayoutParams(gp);grid.addView(item);item.setOnClickListener(v->{try{startActivity(launch);finish();}catch(Exception ex){Toast.makeText(this,"Не вдалося відкрити програму",Toast.LENGTH_SHORT).show();}});item.setOnLongClickListener(v->{appMenu(pkg,label);return true;});}sv.addView(grid,new ScrollView.LayoutParams(-1,-2));LinearLayout.LayoutParams svp=new LinearLayout.LayoutParams(-1,0,1);Ui.margins(svp,this,0,8,0,0);panel.addView(sv,svp);
 TextView hint=Ui.text(this,"Натисни поза папкою, щоб закрити",11,0xDDFFFFFF);hint.setGravity(Gravity.CENTER);panel.addView(hint,Ui.mp(this));int ww=(int)(getResources().getDisplayMetrics().widthPixels*("small".equals(f.popupSize)?.72:"large".equals(f.popupSize)?.96:.88));int hh=(int)(getResources().getDisplayMetrics().heightPixels*("small".equals(f.popupSize)?.42:"large".equals(f.popupSize)?.78:.60));FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(ww,hh,Gravity.CENTER);outer.addView(panel,pp);setContentView(outer);animate(panel);}
 void appMenu(String pkg,String label){new AlertDialog.Builder(this).setTitle(label).setItems(new String[]{"Видалити з папки","Інформація про програму"},(d,w)->{if(w==0){f.packages.remove(pkg);new FolderStore(this).save(f);FolderWidgetProvider.updateAll(this);recreate();}else{Intent i=new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,android.net.Uri.parse("package:"+pkg));startActivity(i);}}).show();}
 void animate(View v){if("none".equals(f.animation))return;if("fade".equals(f.animation)){v.setAlpha(0f);v.animate().alpha(1f).setDuration(180).start();}else if("slide".equals(f.animation)){v.setTranslationY(Ui.dp(this,120));v.setAlpha(0f);v.animate().translationY(0).alpha(1).setDuration(220).start();}else if("spring".equals(f.animation)){v.setScaleX(.72f);v.setScaleY(.72f);v.setAlpha(0f);v.animate().scaleX(1).scaleY(1).alpha(1).setDuration(340).setInterpolator(new OvershootInterpolator(1.5f)).start();}else{v.setScaleX(.82f);v.setScaleY(.82f);v.setAlpha(0f);v.animate().scaleX(1).scaleY(1).alpha(1).setDuration(200).start();}}
}
