package com.customfolders.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 FolderStore store;LinearLayout list;
 @Override public void onCreate(Bundle b){ThemeUtils.apply(this);super.onCreate(b);store=new FolderStore(this);build();}
 @Override protected void onResume(){super.onResume();refresh();}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,14));root.setBackgroundColor(ThemeUtils.bg(this));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=Ui.text(this,"Мої папки",27,ThemeUtils.text(this));title.setTypeface(Typeface.DEFAULT_BOLD);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button templates=Ui.button(this,"Шаблони",false);top.addView(templates,new LinearLayout.LayoutParams(-2,Ui.dp(this,42)));Button settings=Ui.button(this,"⚙",false);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(Ui.dp(this,50),Ui.dp(this,42));Ui.margins(sp,this,8,0,0,0);top.addView(settings,sp);root.addView(top,Ui.mp(this));TextView sub=Ui.text(this,"Створюй власні папки-віджети для програм і оформлюй їх під свій робочий стіл.",14,ThemeUtils.sub(this));LinearLayout.LayoutParams sb=Ui.mp(this);Ui.margins(sb,this,0,8,0,10);root.addView(sub,sb);ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list,new ScrollView.LayoutParams(-1,-2));root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));Button add=Ui.button(this,"+ Створити папку",true);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,Ui.dp(this,54));Ui.margins(ap,this,0,10,0,0);root.addView(add,ap);setContentView(root);add.setOnClickListener(v->startActivity(new Intent(this,EditorActivity.class)));templates.setOnClickListener(v->startActivity(new Intent(this,TemplatesActivity.class)));settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));}
 void refresh(){if(list==null)return;list.removeAllViews();List<FolderStore.Folder>a=store.all();if(a.isEmpty()){LinearLayout c=Ui.card(this);TextView t=Ui.text(this,"Папок ще немає. Створи першу — після збереження її можна додати на робочий стіл.",16,ThemeUtils.sub(this));t.setPadding(0,Ui.dp(this,18),0,Ui.dp(this,18));t.setGravity(Gravity.CENTER);c.addView(t,Ui.mp(this));list.addView(c,Ui.mp(this));return;}for(FolderStore.Folder f:a){LinearLayout c=Ui.card(this);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);ImageView prev=new ImageView(this);prev.setScaleType(ImageView.ScaleType.FIT_XY);prev.setImageBitmap(WidgetRenderer.render(this,f,Ui.dp(this,80),Ui.dp(this,80)));row.addView(prev,new LinearLayout.LayoutParams(Ui.dp(this,80),Ui.dp(this,80)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);TextView n=Ui.text(this,f.name,18,ThemeUtils.text(this));n.setTypeface(Typeface.DEFAULT_BOLD);info.addView(n,Ui.mp(this));TextView d=Ui.text(this,f.packages.size()+" програм • "+labelAnim(f.animation),13,ThemeUtils.sub(this));info.addView(d,Ui.mp(this));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(0,-2,1);Ui.margins(ip,this,12,0,0,0);row.addView(info,ip);Button more=Ui.button(this,"⋮",false);row.addView(more,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,46)));c.addView(row,Ui.mp(this));LinearLayout.LayoutParams cp=Ui.mp(this);Ui.margins(cp,this,0,5,0,7);list.addView(c,cp);c.setOnClickListener(v->{Intent i=new Intent(this,EditorActivity.class).putExtra("folderId",f.id);startActivity(i);});more.setOnClickListener(v->menu(f));}}
 void menu(FolderStore.Folder f){String[] x={"Відкрити","Додати на робочий стіл","Дублювати","Видалити"};new AlertDialog.Builder(this).setTitle(f.name).setItems(x,(d,w)->{if(w==0)startActivity(new Intent(this,FolderPopupActivity.class).putExtra("folderId",f.id));else if(w==1)pin(f.id);else if(w==2){store.duplicate(f.id);refresh();}else new AlertDialog.Builder(this).setTitle("Видалити папку?").setMessage("Програми не видаляються — лише ця папка та її налаштування.").setNegativeButton("Скасувати",null).setPositiveButton("Видалити",(a,b)->{store.delete(f.id);FolderWidgetProvider.updateAll(this);refresh();}).show();}).show();}
 void pin(long id){if(Build.VERSION.SDK_INT>=26){android.appwidget.AppWidgetManager m=android.appwidget.AppWidgetManager.getInstance(this);ComponentName p=new ComponentName(this,FolderWidgetProvider.class);if(m.isRequestPinAppWidgetSupported()){getSharedPreferences("settings",0).edit().putLong("pending_pin",id).apply();m.requestPinAppWidget(p,null,null);Toast.makeText(this,"Підтвердь додавання віджета на робочий стіл",Toast.LENGTH_LONG).show();return;}}Toast.makeText(this,"Додай віджет «Мої папки» через меню віджетів лаунчера",Toast.LENGTH_LONG).show();}
 String labelAnim(String s){if("fade".equals(s))return"Fade";if("slide".equals(s))return"Slide Up";if("spring".equals(s))return"Spring";if("none".equals(s))return"Без анімації";return"Zoom";}
}
