package com.customfolders.app;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;
public class SettingsActivity extends Activity{
 static final int EXP=50,IMP=51;FolderStore store;
 @Override public void onCreate(Bundle b){ThemeUtils.apply(this);super.onCreate(b);store=new FolderStore(this);build();}
 void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,24));root.setBackgroundColor(ThemeUtils.bg(this));sv.addView(root,new ScrollView.LayoutParams(-1,-2));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);Button back=Ui.button(this,"←",false);top.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,42)));TextView t=Ui.text(this,"Налаштування",24,ThemeUtils.text(this));t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);Ui.margins(tp,this,10,0,0,0);top.addView(t,tp);root.addView(top,Ui.mp(this));back.setOnClickListener(v->finish());section(root,"Тема редактора");RadioGroup rg=new RadioGroup(this);String[] nm={"Як у системі","Світла","Темна"};String[] val={"system","light","dark"};for(int i=0;i<3;i++){RadioButton r=new RadioButton(this);r.setText(nm[i]);r.setTextColor(ThemeUtils.text(this));r.setId(100+i);rg.addView(r);if(val[i].equals(ThemeUtils.mode(this)))r.setChecked(true);}root.addView(rg,Ui.mp(this));rg.setOnCheckedChangeListener((g,id)->{ThemeUtils.setMode(this,val[id-100]);recreate();});section(root,"Резервна копія");LinearLayout card=Ui.card(this);TextView desc=Ui.text(this,"Експорт містить усі папки, їх стилі, порядок програм і власні шаблони. Зображення-фони залишаються посиланнями на файли пристрою, тому після перенесення на інший телефон їх може знадобитися вибрати повторно.",13,ThemeUtils.sub(this));card.addView(desc,Ui.mp(this));Button ex=Ui.button(this,"Експортувати",true),im=Ui.button(this,"Імпортувати",false);LinearLayout.LayoutParams ep=Ui.mp(this);Ui.margins(ep,this,0,10,0,0);card.addView(ex,ep);LinearLayout.LayoutParams ip=Ui.mp(this);Ui.margins(ip,this,0,7,0,0);card.addView(im,ip);root.addView(card,Ui.mp(this));ex.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"moi-papky-backup.json");startActivityForResult(i,EXP);});im.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");startActivityForResult(i,IMP);});section(root,"Про застосунок");LinearLayout about=Ui.card(this);about.addView(Ui.text(this,"Мої папки • 1.0.0\nКастомні папки-віджети поверх штатного робочого столу Android/HyperOS.",13,ThemeUtils.sub(this)),Ui.mp(this));root.addView(about,Ui.mp(this));setContentView(sv);}
 void section(LinearLayout r,String s){TextView t=Ui.text(this,s,15,ThemeUtils.text(this));t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams p=Ui.mp(this);Ui.margins(p,this,0,18,0,7);r.addView(t,p);}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();try{if(req==EXP){try(OutputStream o=getContentResolver().openOutputStream(u,"wt")){o.write(store.exportAll().getBytes(StandardCharsets.UTF_8));}Toast.makeText(this,"Резервну копію створено",Toast.LENGTH_SHORT).show();}else{try(InputStream in=getContentResolver().openInputStream(u)){ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] x=new byte[8192];int n;while((n=in.read(x))>0)b.write(x,0,n);store.importAll(b.toString("UTF-8"));}FolderWidgetProvider.updateAll(this);Toast.makeText(this,"Імпорт завершено",Toast.LENGTH_SHORT).show();}}catch(Exception e){new AlertDialog.Builder(this).setTitle("Помилка").setMessage(e.getMessage()).setPositiveButton("OK",null).show();}}
}
