package com.customfolders.app;
import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import java.io.*;import java.util.*;
public final class WidgetRenderer{
 private WidgetRenderer(){}
 public static Bitmap render(Context c,FolderStore.Folder f,int w,int h){w=Math.max(w,96);h=Math.max(h,96);Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas cv=new Canvas(b);Paint p=new Paint(3);int color;try{color=Color.parseColor(f.color);}catch(Exception e){color=Color.rgb(108,99,255);}color=Color.argb(Math.max(30,Math.min(255,f.opacity)),Color.red(color),Color.green(color),Color.blue(color));float r="circle".equals(f.shape)?Math.min(w,h)/2f:"square".equals(f.shape)?4f:Math.min(w,h)*.16f;Path clip=new Path();RectF rr=new RectF(3,3,w-3,h-3);clip.addRoundRect(rr,r,r,Path.Direction.CW);cv.save();cv.clipPath(clip);p.setColor(color);cv.drawRect(0,0,w,h,p);Bitmap bg=loadUri(c,f.bgUri);if(bg!=null){Rect src=new Rect(0,0,bg.getWidth(),bg.getHeight());RectF dst=crop(bg.getWidth(),bg.getHeight(),w,h);p.setAlpha(Math.max(80,f.opacity));cv.drawBitmap(bg,src,dst,p);}cv.restore();
  int pad=Math.max(8,w/16), top=pad; if(f.showTitle){p.setColor(Color.WHITE);p.setTextSize(Math.max(14,Math.min(26,h/7f)));p.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));p.setShadowLayer(3,0,1,0x88000000);cv.drawText(ellipsize(f.name,16),pad,top+p.getTextSize(),p);top+=(int)(p.getTextSize()+6);}
  Bitmap custom=loadUri(c,f.iconUri);if(custom!=null){int s=Math.min(w,h)/3;cv.drawBitmap(custom,null,new RectF(w-s-pad,pad,w-pad,pad+s),p);}else if(f.emoji!=null&&!f.emoji.isEmpty()){p.clearShadowLayer();p.setTextSize(Math.min(w,h)/3f);p.setTextAlign(Paint.Align.RIGHT);cv.drawText(f.emoji,w-pad,pad+p.getTextSize(),p);p.setTextAlign(Paint.Align.LEFT);} 
  PackageManager pm=c.getPackageManager();int count=Math.min(f.previewCount,f.packages.size());if(count>0){int cols=count<=4?2:3;int rows=(int)Math.ceil(count/(double)cols);int availH=h-top-pad;int cell=Math.min((w-pad*2)/cols,Math.max(24,availH/Math.max(1,rows)));int icon=(int)(cell*.62);for(int i=0;i<count;i++){int row=i/cols,col=i%cols;int cx=pad+col*cell+(cell-icon)/2,cy=top+row*cell+(cell-icon)/2;try{Drawable d=pm.getApplicationIcon(f.packages.get(i));Bitmap ib=drawableBitmap(d,icon,icon);cv.drawBitmap(ib,null,new RectF(cx,cy,cx+icon,cy+icon),p);}catch(Exception ignored){}}}
  return b;}
 private static String ellipsize(String s,int n){return s.length()<=n?s:s.substring(0,n-1)+"…";} private static RectF crop(int bw,int bh,int w,int h){float bs=bw/(float)bh,ts=w/(float)h;if(bs>ts){float nw=bh*ts, left=(bw-nw)/2f;return new RectF(-left*w/nw,0,w+(left*w/nw),h);}else{float nh=bw/ts,top=(bh-nh)/2f;return new RectF(0,-top*h/nh,w,h+(top*h/nh));}}
 public static Bitmap loadUri(Context c,String s){if(s==null||s.isEmpty())return null;try(InputStream in=c.getContentResolver().openInputStream(Uri.parse(s))){return BitmapFactory.decodeStream(in);}catch(Exception e){return null;}}
 public static Bitmap drawableBitmap(Drawable d,int w,int h){Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);d.setBounds(0,0,w,h);d.draw(c);return b;}
}
